version: '2.3'
services:

  zookeeper:
    image: confluentinc/cp-zookeeper:5.3.0
    restart: always
    hostname: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: nc -z localhost 2181 || exit -1
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 10s

  syncer:
    image: sentinelhub/rate-limiting-guard
    container_name: syncer
    build:
      context: ./syncer/
      dockerfile: Dockerfile
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
      CLIENT_ID: "${CLIENT_ID}"
      CLIENT_SECRET: "${CLIENT_SECRET}"
      ZOOKEEPER_HOSTS: "zookeeper:2181"
